# Generated by Django 5.2.8 on 2025-11-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color_vehiculo', models.CharField(choices=[('rojo', 'Rojo'), ('azul', 'Azul'), ('negro', 'Negro'), ('blanco', 'Blanco'), ('gris', 'Gris')], default='negro', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='vehiculo',
        ),
    ]
